# Docker Compose Override for Local Development
# This file automatically configures the local domain setup
# It's automatically loaded by docker-compose

version: '3.8'

services:
  # Override nginx to include domain setup
  nginx:
    environment:
      - DOMAIN_SETUP=true
    volumes:
      # Mount the domain setup script
      - ./setup-local-domain.sh:/usr/local/bin/setup-domain.sh:ro
    # Add a custom entrypoint that sets up the domain
    entrypoint: |
      sh -c '
        echo "🌐 Setting up local domain..."
        if [ -f "/usr/local/bin/setup-domain.sh" ]; then
          chmod +x /usr/local/bin/setup-domain.sh
          /usr/local/bin/setup-domain.sh add || echo "⚠️ Domain setup failed, continuing..."
        fi
        echo "🚀 Starting nginx..."
        nginx -g "daemon off;"
      '

  # Override client to use custom domain
  client:
    environment:
      - VITE_API_URL=https://event-i.local
    depends_on:
      - nginx

  # Override server to trust proxy and use custom domain
  server:
    environment:
      - FRONTEND_URL=https://event-i.local
      - BASE_URL=https://event-i.local
    depends_on:
      - nginx
