apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-i-staging

resources:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: server
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: server
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "512Mi"
              cpu: "250m"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: client
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: client
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - frontend-url=https://staging.event-i.co.ke
  - payhero-callback-url=https://staging.event-i.co.ke/api/payhero/callback
  - payhero-success-url=https://staging.event-i.co.ke/checkout/success
  - payhero-failed-url=https://staging.event-i.co.ke/checkout/failed
